const resList = [
  {
    id: "80802",
    name: "Third Wave Coffee",
    cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
    locality: "Armane Nagar",
    areaName: "Sadashiv Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Beverages", "Bakery", "Continental"],
    avgRating: 4.4,
  },
  {
    id: "281469",
    name: "Lavonne",
    cloudinaryImageId: "emlehbuwgsmryxhwzhvq",
    locality: "St. Marks Road",
    areaName: "St. Marks Road",
    costForTwo: "₹750 for two",
    cuisines: ["Bakery", "Desserts"],
    avgRating: 4.6,
  },
  {
    id: "43836",
    name: "McDonald's",
    cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
    locality: "MG Road",
    areaName: "Ashok Nagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: 4.3,
  },
  {
    id: "23847",
    name: "Domino's Pizza",
    cloudinaryImageId: "fjqcvqfgqlw6h0atques",
    locality: "Rest House Road",
    areaName: "Brigade Road",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 3.3,
  },
  {
    id: "279060",
    name: "Sikandar Rolls",
    cloudinaryImageId: "m6c0uvtstsvvnzb99fkm",
    locality: "Barton Centre",
    areaName: "M G Road",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Kebabs", "Beverages", "Desserts"],
    avgRating: 4.6,
  },
  {
    id: "16073",
    name: "California Burrito",
    cloudinaryImageId: "27238ee4292d42c7b705f2ce8671ff80",
    locality: "Malleshwaram",
    areaName: "Malleshwaram",
    costForTwo: "₹250 for two",
    cuisines: [
      "Mexican",
      "American",
      "Salads",
      "Continental",
      "Keto",
      "Healthy Food",
    ],
    avgRating: 3.7,
  },
  {
    id: "614642",
    name: "Soul Rasa",
    cloudinaryImageId: "v9fczzlua1wnrx63fh1g",
    locality: "Akkithimanahalli",
    areaName: "Shanti Nagar",
    costForTwo: "₹400 for two",
    cuisines: [
      "Indian",
      "Healthy Food",
      "Home Food",
      "South Indian",
      "North Indian",
    ],
    avgRating: 4.6,
  },
  {
    id: "69876",
    name: "Subway",
    cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
    locality: "UB City",
    areaName: "Ashok Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4.1,
  },
  {
    id: "396741",
    name: "Faasos - Wraps, Rolls & Shawarma",
    cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
    locality: "Residency Road",
    areaName: "Shantinagar",
    costForTwo: "₹200 for two",
    cuisines: ["Kebabs", "Fast Food", "Snacks"],
    avgRating: 4.3,
  },
  {
    id: "448116",
    name: "The Bowl Company",
    cloudinaryImageId: "bb6049fae59b8a2413a9177eb0338b49",
    locality: "Akkithimanahalli",
    areaName: "Shanti Nagar",
    costForTwo: "₹300 for two",
    cuisines: [
      "Pan-Asian",
      "Continental",
      "North Indian",
      "Desserts",
      "American",
      "Asian",
    ],
    avgRating: 3.5,
  },
  {
    id: "464509",
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
    locality: "Pulkeshi Nagar",
    areaName: "Frazer Town",
    costForTwo: "₹300 for two",
    cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
    avgRating: 4.4,
  },
  {
    id: "792403",
    name: "Nandhana Palace",
    cloudinaryImageId: "502d6ccc803e95343d0324b15f8639da",
    locality: "Jayanagar",
    areaName: "Jayanagar",
    costForTwo: "₹500 for two",
    cuisines: ["Andhra", "North Indian"],
    avgRating: 4.4,
  },
  {
    id: "534235",
    name: "Cheesecake & Co.",
    cloudinaryImageId: "40b0a201eadbec469c2f9a06d5e7c722",
    locality: "6th Block",
    areaName: "Koramangala",
    costForTwo: "₹250 for two",
    cuisines: ["Bakery"],
    avgRating: 3.9,
  },
  {
    id: "3241",
    name: "Meghana Foods",
    cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
    locality: "Residency Road",
    areaName: "Residency Road",
    costForTwo: "₹500 for two",
    cuisines: [
      "Biryani",
      "Andhra",
      "South Indian",
      "North Indian",
      "Chinese",
      "Seafood",
    ],
    avgRating: 4.6,
  },
  {
    id: "506324",
    name: "Louis Burger",
    cloudinaryImageId: "19d3d352cc815b9d88b22617b41fa97b",
    locality: "6Th Block, Koramangala",
    areaName: "Koramangala",
    costForTwo: "₹600 for two",
    cuisines: ["Burgers", "American", "Fast Food"],
    avgRating: 4.4,
  },
];

export default resList;